summary_result_file:  "results.csv"
root_folder: "rosbag2_throughput_results"
delete_bags: true
test_matrix:
  max_cache_size: 0
  storage_configs:
    - [mcap, mcap_basic.yaml]
    - [mcap, mcap_basic.yaml]
    - [sqlite, sqlite_optimized.yaml]
    - [sqlite, sqlite_resilient.yaml]
  producers:
    - topics: 0
      size_per_msg: 0
      messages_per_topic: 0
    - topics: 1
      messages_per_topic: 100
      size_per_msg: 1000
    - topics: 1
      messages_per_topic: 1000
      size_per_msg: 1000
    - topics: 1
      size_per_msg: 1000000
      messages_per_topic: 1000
    - topics: 10
      size_per_msg: 1000
      messages_per_topic: 1000
    - topics: 100
      size_per_msg: 1000
      messages_per_topic: 100
